- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/ftp/{{ item }}
    state: directory
    mode: '0755'

- name: ftp - Copy default boot config file
  ansible.builtin.copy:
    src: /var/ftp/{{ item.os_version }}/boot.cfg
    dest: /var/ftp/{{ item.os_version }}/boot-{{ item.os_version }}.cfg
    remote_src: yes

- name: ftp - Add foreman server fqdn to boot cfg file
  ansible.builtin.lineinfile:
    path: /var/ftp/{{ item.os_version }}/boot-{{ item.os_version}}.cfg
    regexp: '^prefix='
    line: prefix=ftp://{{ foreman_host }}/{{ item.os_version }}
    create: yes
