- name: ipxe - Configure DHCP to use iPXE
  blockinfile:
    path: /etc/dhcp/dhcpd.conf
    insertafter: 'filename "pxelinux.0"[\r\n]+}'
    block: |
      if exists user-class and option user-class = "iPXE" {
        filename "http://uk1sxlx00219.corpnet2.com/unattended/iPXE?bootstrap=1";  # Replace with actual FQDN of Foreman Server
      } elsif option architecture = 00:06 {
        filename "ipxe.efi";
      } elsif option architecture = 00:07 {
        filename "snp.efi";
      } elsif option architecture = 00:09 {
        filename "ipxe.efi";
      } else {
        filename "undionly.kpxe";
      }
  notify: Restart DHCP service

- name: ipxe - clone_ipxe - check if ipxe dir already exists
  stat:
    path: /tmp/ipxe
  register: ipxe_dir

- name: ipxe - clone_ipxe - check ipxe current branch
  shell: >
    cd /tmp/ipxe &&
    git branch |head -n1
  register: ipxe_current_branch
  when:
    - ipxe_dir.stat.exists

- name: ipxe - clone_ipxe - get ipxe directory status
  find:
    paths: /tmp/ipxe
    file_type: directory
  register: ipxe_directory

- name: ipxe - clone_ipxe - hard-reset ipxe HEAD to desired commit
  shell: >
    cd /tmp/ipxe &&
    git checkout {{ ipxe_git_commit_checksum }} &&
    git reset --hard {{ ipxe_git_commit_checksum }}
  register: ipxe_switch_head
  when:
    - ipxe_dir.stat.exists
    - not ipxe_git_commit_checksum[:7] in ipxe_current_branch.stdout
    - ipxe_directory.examined != 0  # when not empty

- name: ipxe - clone_ipxe - clone ipxe if dir does not exist or is empty
  shell: >
    git clone https://github.com/ipxe/ipxe /tmp/ipxe &&
    cd /tmp/ipxe &&
    git checkout "{{ ipxe_git_commit_checksum }}"
  when:
    - (not ipxe_dir.stat.exists) or (ipxe_directory.examined == 0)  # when empty

- name: ipxe - Delete general.h config file. Needed because cannot make uefi binary (snp.efi) with flags needed for legacy one that are added later in this task
  ansible.builtin.file:
    path: /tmp/ipxe/src/config/local/general.h
    state: absent

- name: ipxe - Patch ipxe to enable FTP functionality
  ansible.builtin.lineinfile:
    path: /tmp/ipxe/src/config/local/general.h
    regexp: '^.*DOWNLOAD_PROTO_FTP'
    line: "#define  DOWNLOAD_PROTO_FTP"
    create: yes

- name: ipxe - Patch ipxe to disable IPv6 functionality
  ansible.builtin.lineinfile:
    path: /tmp/ipxe/src/config/local/general.h
    regexp: '^.*NET_PROTO_IPV6'
    line: "#undef NET_PROTO_IPV6"
    create: yes
  when: not enable_ipv6_in_ipxe

- name: ipxe - Checksum bin-x86_64-efi/snp.efi
  ansible.builtin.stat:
    path: /tmp/ipxe/src/bin-x86_64-efi/snp.efi
    get_checksum: yes
  register: snp_file_info

- name: ipxe - initialise snp_checksum_from_file
  set_fact: snp_checksum_from_file=init

- name: ipxe - set checksum if snp file exists
  set_fact: snp_checksum_from_file={{ snp_file_info.stat.checksum }}
  when: snp_file_info.stat.checksum is defined

- name: ipxe - Build snp.kpxe from ipxe project
  shell: |
    cd /tmp/ipxe/src
    make bin-x86_64-efi/snp.efi
  when: snp_checksum_from_file != ipxe_snp_checksum

- name: ipxe - Patch ipxe to enable Syslinux Comboot support
  ansible.builtin.lineinfile:
    path: /tmp/ipxe/src/config/local/general.h
    regexp: '^.*IMAGE_COMBOOT'
    line: "#define  IMAGE_COMBOOT"
    create: yes

- name: ipxe - Patch ipxe to increase MAX_MODULES
  ansible.builtin.lineinfile:
    path: /tmp/ipxe/src/arch/x86/image/multiboot.c
    regexp: '^.*MAX_MODULES 8'
    line: "#define MAX_MODULES 100"
  when:
    - ipxe_enabled

- name: ipxe - Checksum bin/undionly.kpxe
  ansible.builtin.stat:
    path: /tmp/ipxe/src/bin/undionly.kpxe
    get_checksum: yes
  register: undionly_file_info

- name: ipxe - initialise undionly_checksum_from_file
  set_fact: undionly_checksum_from_file=init

- name: ipxe - set checksum if undionly file exists
  set_fact: undionly_checksum_from_file={{ undionly_file_info.stat.checksum }}
  when:
    - undionly_file_info.stat.checksum is defined

- name: ipxe - Build undionly.kpxe from ipxe project
  shell: |
    cd /tmp/ipxe/src
    make bin/undionly.kpxe
  when:
    - undionly_checksum_from_file != ipxe_undionly_checksum
    - not config_only

- name: ipxe - copy files remote to remote
  copy:
    src: /tmp/ipxe/src/{{ item }}
    dest: /var/lib/tftpboot/
    remote_src: yes
  with_list:
    - bin/undionly.kpxe
    - bin-x86_64-efi/snp.efi
  when:
    - not config_only

- name: ipxe - recursively change ownership of tftproot directory
  ansible.builtin.file:
    path: /var/lib/tftpboot
    state: directory
    recurse: yes
    owner: foreman-proxy
    group: root
